# Generated by Django 5.2.15 on 2026-10-04 12:42

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0122_alter_draftissue_assignees_alter_issue_assignees_and_more'),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='AIContextEmbedding',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('entity_type', models.CharField(choices=[('work_item', 'Work Item'), ('comment', 'Comment'), ('page', 'Page'), ('project', 'Project'), ('cycle', 'Cycle'), ('module', 'Module')], max_length=32)),
                ('entity_id', models.CharField(db_index=True, max_length=255)),
                ('chunk_index', models.PositiveIntegerField(default=0)),
                ('content_hash', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(null=True)),
                ('embedding_model', models.CharField(max_length=255)),
                ('embedding_dimensions', models.PositiveIntegerField(default=1536)),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_embeddings', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_embeddings', to='db.workspace')),
            ],
            options={
                'verbose_name': 'AI Context Embedding',
                'verbose_name_plural': 'AI Context Embeddings',
                'db_table': 'ai_context_embeddings',
                'indexes': [models.Index(fields=['workspace', 'entity_type'], name='ai_embed_ws_entity_idx'), models.Index(fields=['embedding_model'], name='ai_embed_model_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('entity_type', 'entity_id', 'chunk_index'), name='ai_embedding_unique_entity_chunk_when_not_deleted')],
            },
        ),
        migrations.CreateModel(
            name='AITaskLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('task', models.CharField(max_length=64)),
                ('provider', models.CharField(blank=True, max_length=32, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], default='success', max_length=16)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_task_logs', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_task_logs', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_task_logs', to='db.workspace')),
            ],
            options={
                'verbose_name': 'AI Task Log',
                'verbose_name_plural': 'AI Task Logs',
                'db_table': 'ai_task_logs',
                'indexes': [models.Index(fields=['workspace', 'user', 'created_at'], name='ai_task_log_ws_user_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceAIConfiguration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('provider', models.CharField(default='openai', max_length=32)),
                ('api_key', models.TextField(blank=True, null=True)),
                ('base_url', models.CharField(blank=True, max_length=512, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('embedding_model', models.CharField(blank=True, max_length=255, null=True)),
                ('embedding_dimensions', models.PositiveIntegerField(default=1536)),
                ('embedding_max_tokens', models.PositiveIntegerField(default=8191)),
                ('context_window', models.PositiveIntegerField(default=128000)),
                ('max_output_tokens', models.PositiveIntegerField(default=4096)),
                ('reserved_tokens', models.PositiveIntegerField(default=256)),
                ('temperature', models.FloatField(default=0.2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_ai_configuration', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Workspace AI Configuration',
                'verbose_name_plural': 'Workspace AI Configurations',
                'db_table': 'workspace_ai_configurations',
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace',), name='workspace_ai_config_unique_workspace_when_not_deleted')],
            },
        ),
    ]
